# Generated by Django 5.0.6 on 2024-06-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('age', models.CharField(max_length=100, verbose_name='Yaş')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Doğum Tarixi')),
                ('location', models.CharField(max_length=100, verbose_name='Yer')),
                ('education', models.CharField(max_length=100, verbose_name='Təhsil')),
                ('skills', models.CharField(max_length=100, verbose_name='Bacarıqlar')),
                ('experience', models.CharField(max_length=100, verbose_name='Təcrübə')),
                ('project', models.CharField(max_length=100, verbose_name='Proyekt')),
                ('contact', models.CharField(max_length=100, verbose_name='Əlaqə')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
